# Site settings
title: SlicerHeart
tagline: SlicerHeart
author: 
first_button_text: 'Find out more'
first_button_url: '#install'
header_img: #
home_menu_text: Home
home_menu_img: /img/logo.png
description: Tools for cardiac image import (3D/4D ultrasound, CT, MRI), quantification, surgical planning, and implant placement planning and assessment.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://slicerheart.github.io/" # the base hostname & protocol for your site

# Theme customization
primary: '#981616'
dark: '#555'

# Contact details
email: JOLLEYM@chop.edu
github_username: slicerheart/slicerheart
linkedin_username: jolleylab
youtube_username: jolleylab

# Data collections
collections:
  blocks:
    output: false
  gallery:
    output: false

# Build settings
markdown: kramdown

exclude:
  - serve
  - README.md
  - LICENCE

